spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser

info:
  name: Spring Data Rest
  description: This app is used for CRUD operations with employees of company
  author: liuminol

management:
  endpoints:
    web:
      exposure:
        include: "*"