spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritycourse?serverTimezone=Europe/Moscow
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bestuser
    password: bestuser

server:
  port: 8000